;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from bogus-operandi-theme.el

(put 'bogus-operandi 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))



;;; Generated autoloads from bogus-operandi-theme-backup.el

(put 'bogus-operandi 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))


;;; Generated autoloads from bogus-themes.el

(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (equal dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))


;;; Generated autoloads from utils.el

(register-definition-prefixes "utils" '("grayscale"))


;;; Generated autoloads from bogus-vivendi-theme.el

(put 'bogus-vivendi 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'modus))

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
